<?php

/**
 * @file
 * File (Field) Paths module integration.
 *
 * @deprecated in filefield_paths:8.x-1.0 and is removed from
 *   filefield_paths:2.0.0. See moved hooks implementations in appropriate
 *   places.
 *
 * @see https://www.drupal.org/node/3562299
 */

@trigger_error(__FILE__ . ' is deprecated in filefield_paths:8.x-1.0 and is removed from filefield_paths:2.0.0. See moved hooks implementations in appropriate places. See https://www.drupal.org/node/3562299', E_USER_DEPRECATED);
