# Schema for the File (Field) Paths module.

field.field.*.*.*.third_party.filefield_paths:
  type: mapping
  label: 'FileField Path settings'
  mapping:
    enabled:
      type: boolean
      label: 'Enabled'
    filepath:
      type: string
      label: 'Path'
    path_options:
      type: mapping
      label: 'Path options'
      mapping:
        clean_path:
          type: boolean
          label: 'Path clean with Pathauto'
        transliterate_path:
          type: boolean
          label: 'Transliterate path'
    filename:
      type: string
      label: 'Filename'
    name_options:
      type: mapping
      label: 'Name options'
      mapping:
        clean_name:
          type: boolean
          label: 'Filename clean with Pathauto'
        transliterate_name:
          type: boolean
          label: 'Transliterate filename'
    retroactive_update:
      type: boolean
      label: 'Retroactive'
    active_updating:
      type: boolean
      label: 'Active'
